davbrican/InnoBuddy

- .gitignore
- src/commands/start.py
- src/handlers.py
- src/main.py
Se crea una estructura para el proyecto, además de añadir una plantilla para el gitignore
> style: Estructura base del proyecto

- src/commands/evidencias.py
- src/commands/mensajes.json
- src/commands/readMesssage.py
- src/handlers.py
Se agrega un comando para informar sobre como crear una evidencia. Además, se crea añade un archivo de configuración de mensajes.
> feat: Agregación comando información evidencias

- src/main.py
- src/tests/test_commands.py
Se ejecuta el bot con el token de pruebas mientras se ejecutan los tests. También parametrizada la función master para ejecutarse con un token u otro. Espero que sirva para simplificar la implementación del CI. Salud!
> fix: Ejecuta bot de pruebas mientras se ejecutan tests

- workflows/innobuddy.yml
Se añade el CI, donde se levanta un mysql y se ejecutan los tests de la aplicación siempre que se haga push o pull request a master o develop
> feat: Agregación de CI con tests

- src/commands/eventos.py
- src/commands/mensajes.json
- src/commands/readMesssage.py
- src/db/populate.py
- src/handlers.py
- src/repositories/events_repository.py
- src/services/events_service.py
Se añade el comando de eventos donde se permite listar todos los eventos de la jornada actual de Innosoft (/eventos) y además listar los eventos de un día concreto (/eventos YYYY-MM-DD).
> feat: Agregación comando eventos

- src/commands/eventos.py
- src/commands/mensajes.json
- src/db/populate.py
- src/repositories/events_repository.py
- src/services/events_service.py
Con el comando "/eventos hoy" podras ver los eventos exclusivos del día actual en el que te encuentres.
> feat: Funcionalidad ver los eventos del día actual

- src/commands/valoraciones.json
- src/commands/valoraciones.py
- src/db/populate.py
- src/handlers.py
- src/queries.py
- src/tests/test_commands.py
Borra el mensaje de valoracion, tras valorar un comando
> feat: borrado de mensaje tras valorar

- src/commands/mensajes.json
- src/handlers.py
Añade al menú nuevos comandos, que no estaban registrados anteriormente
> feat: Añadido nuevos comandos

- src/tests/test_commands.py
Se añade el test del comando fechas
> feat: Pruebas comando fechas

- .github/workflows/innobuddy.yml
Se cambia la forma de ejecutar los tests en el CI. Se realizan dos jobs en paralelo, de modo que uno de ellos ejecuta la aplicación y otro ejecuta los tests.
> fix: ejecución tests CI

- src/tests/test_commands.py
Se crean los tests del comando localización.
> feat: Pruebas comando localización

- requirements.txt
- src/tests/README.md
- src/tests/locustfile.py
Se añaden los tests de carga del bot.
> feat: Agregación tests de carga

- .github/workflows/python.yml
Se realiza una refactorización del CI
> refactor: CI sintaxis

- docker/Dockerfile
- docker/docker-compose.yml
Se crea el Dokerfile y el docker-compose.yml para realizar el despliegue con docker.
Para probar que funciona:
cd CARPETA del PROYECTO
docker-compose -f ./docker/docker-compose.yml --project-directory . up
La primera vez es necesario crear la base de datos:
docker exec -it ID_CONTENEDOR python ./src/db/populate.py
> env: Despliegue con Docker

- src/commands/mensajes.json
- src/handlers.py
Se añade un nuevo comando al menú, el comando /recordatorios, también se añade su mensaje correspondiente en mensajes.json
> feat: Añadido el comando /recordatorios

- src/tests/test_commands.py
Se añade un nuevo test que comprueba el tamaño de la colección de eventos del día actual, dependiendo del tamaño se espera una salida u otra.
> test: Añadido test para el comando /eventos hoy

- src/tests/test_localizaciones_service.py
Se añade un test unitario del servicio de localizaciones.
> feat: Prueba localización service

- src/tests/test_commands.py
Se añaden tres pruebas nuevas:
- Información comando admin
- Realizar función administrador sin permisos
- Obtener estadísticas
> feat: Añadido tests del comando /admin

- src/commands/recordatorios.py
- src/scripts/queries.py
- src/services/mongodb_service.py
> refactor: Borrado imports innecesarios

- .github/workflows/deploy.yml
Se agrega el workflow para desplegar de manera continua la aplicación en heroku.
> env: Agregación workflow despliegue continuo

- README.md
- src/commands/mensajes.json
> Develop to master
